export const CURATED_SHOWS = [
  "weird studies",
  "filmspotting",
  "the big picture",
  "the rewatchables",
  "blank check",
  "you must remember this",
  "the film comment podcast",
  "the next picture show",
  "the projection booth",
  "pure cinema podcast",
  "unspooled",
  "the cine-files",
  "mubi podcast",
  "little gold men",
  "indiewire's filmmaker toolkit",
  "the director's cut",
  "film at lincoln center podcast",
  "the business",
  "someone else's movie",
  "the curzon film podcast",
  "script apart",
  "team deakins",
  "the important cinema club",
  "faculty of horror",
  "the evolution of horror",
  "the treatment",
  "slate's spoiler specials",
  "now playing",
  "kermode",
  "the empire film podcast",
  "truth & movies",
  "maltin on movies",
  "the plot thickens",
  "the kingcast",
  "wrong reel",
  "show me the meaning",
  "deep cut",
  "cut and splice",
  "verbal diorama",
  "criterioncast",
  "first impressions: thinking aloud about film",
  "eros + massacre",
  "the last thing i saw",
  "the film stage show",
  "filmwax radio",
  "the a24 podcast",
  "the bechdel cast",
  "switchblade sisters",
  "how did this get made",
  "the flop house",
  "we hate movies",
  "this had oscar buzz",
  "soundtracking",
  "the q&a with jeff goldsmith",
  "the movies that made me",
  "the film programme",
  "ecran large",
  "middle class film class",
  "all the right movies",
  "her head in films",
  "dear movies, i love you",
  "the cinematography podcast",
  "the filmmakers podcast",
];

export const FILM_GENRE_NAMES = [
  "tv & film",
  "film reviews",
  "film history",
  "film interviews",
  "tv reviews",
  "after shows",
];

export const FILM_NAME_STEMS = [
  "film",
  "cinem",
  "cine",
  "cinephil",
  "cinefil",
  "movie",
  "kino",
  "pelicul",
  "screen",
  "celluloid",
  "reel",
  "picture",
  "projector",
  "criterion",
  "letterbox",
  "widescreen",
  "matinee",
  "flick",
  "кино",
  "фильм",
  "синема",
  "سينما",
  "فيلم",
  "أفلام",
];

export const SEQUEL_MARKERS = [
  "chapter",
  "part",
  "pt",
  "ii",
  "iii",
  "iv",
  "2",
  "3",
  "4",
  "two",
  "three",
  "four",
  "returns",
  "reloaded",
  "revolutions",
  "resurrections",
  "begins",
  "again",
  "redux",
  "episode",
  "volume",
  "vol",
  "forever",
  "rises",
  "awakens",
  "legacy",
  "origins",
  "capitulo",
  "capitolo",
  "parte",
  "partie",
  "teil",
  "deel",
  "segunda",
  "segundo",
  "deux",
  "trois",
  "zwei",
  "drei",
  "due",
  "tre",
  "dos",
  "tres",
];

export const COMMON_TITLE_WORDS = [
  "her",
  "him",
  "it",
  "us",
  "we",
  "me",
  "you",
  "up",
  "down",
  "out",
  "in",
  "on",
  "no",
  "yes",
  "go",
  "if",
  "she",
  "he",
  "they",
  "them",
  "the",
  "and",
  "or",
  "but",
  "so",
  "home",
  "heat",
  "love",
  "life",
  "room",
  "big",
  "gone",
  "away",
  "drive",
  "alien",
  "time",
  "man",
  "men",
  "women",
  "woman",
  "boy",
  "girl",
  "king",
  "queen",
  "son",
  "father",
  "mother",
  "brother",
  "sister",
  "friends",
  "one",
  "two",
  "dog",
  "cat",
  "car",
  "gun",
  "war",
  "sun",
  "moon",
  "star",
  "stars",
  "water",
  "fire",
  "earth",
  "air",
  "light",
  "dark",
  "night",
  "day",
  "end",
  "start",
  "after",
  "before",
  "now",
  "then",
  "here",
  "there",
  "this",
  "that",
  "what",
  "who",
  "when",
  "why",
  "how",
  "all",
  "some",
  "none",
  "new",
  "old",
];
