package com.lagradost.cloudstream3.extractors

import com.lagradost.cloudstream3.utils.ExtractorApi

fun builtinExtractors(): List<ExtractorApi> = listOf(
    ByseLapuix(),
    ByseKoze(),
    ByseSukior(),
    ByseVepoin(),
    ByseWihe(),
    ByseZejataos(),
    ByseSayeveum(),
    FilemoonByse(),
    FilemoonToByse(),
    FilemoonIn(),
    Gn1r5n(),
    ByseMfw09(),
    ByseTayico(),

    StreamWishTo(),
    StrwishCom(),
    Hlswish(),
    Flaswish(),
    Wishembed(),
    Swiftplayers(),
    Embedwish(),
    Sfastwish(),

    MegaPlay(),
    MegaPlayOne(),
    VidStackIo(),
    UnsBio(),
    UpnsLive(),
    UpnsOne(),
    UpnsInk(),

    Voe(),
    Mp4Upload(),
    StreamTape(),
    Vidmoly(),
    VidmolyBiz(),
    VidmolyNet(),
    LuluStream(),
    LuluVdo(),
    Lulustream1(),
    Lulustream2(),
    Luluvdoo(),
    StreamRuby(),
    StreamHls(),
    StreamHgSwdyu(),
    Hdm2(),
    Blakite(),
    Krakenfiles(),
    MixDrop(),
    MixDropTop(),
    MiiixDrop(),
    VidHide(),
    DoodStream(),
    DoodLi(),
    DoodLaExtractor(),
    DoodstreamCom(),
    DoodYtExtractor(),
    PlayMogo(),
    MyVidPlay(),
    VVide0(),
    Do7Go(),
    OkRu(),
    YourUpload(),

    AnimeAppsPlayer(),

    EmturbovidExtractor(),
    TurboVidHls(),

    PixelDrain(),
    PixelDrainDev(),
    PixelDrainNet(),
    Supervideo(),

    GoogleVideoDownload(),
    DlDokan(),

    DonghuaWorld(),

    VCloud(),

    HubDrive(),
    HubCloudDrive(),
    HubCloudIst(),
    HubCdnWiki(),
    HubCdnClub(),
    HbLinksLol(),
    Xdl(),

    AnimeDekhoWrapper(),
    AnimeWorldWrapper(),
    FilesForeverWrapper(),
    IqSmartGamesWrapper(),

    ToonStream(),
    ToonStreamOne(),
    Rumble(),
    DTube(),
    Dailymotion(),
    DailyMotionShort(),
    DailyMotionGeo(),
    InternetArchive(),
    Invidious(),
    YoutubeExtractor(),
    YoutubeShort(),
    YoutubeNoCookie(),
    TwitchExtractor(),
    TwitchPlayer(),
)
